language: cpp
sudo: false

matrix:
    include:
        - os: osx
          compiler: clang
          env: COMPILER=clang++ BUILD_TYPE=Release
          osx_image: xcode7.2
        - os: osx
          compiler: clang
          env: COMPILER=clang++ BUILD_TYPE=Release
        - os: linux
          compiler: clang
          env: COMPILER=clang++-3.7 BUILD_TYPE=Release
          addons:
              apt:
                  sources:
                      - george-edison55-precise-backports
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-3.7
                  packages:
                      - clang-3.7
                      - cmake
                      - cmake-data
        - os: linux
          compiler: clang
          env: COMPILER=clang++-3.6 BUILD_TYPE=Release
          addons:
              apt:
                  sources:
                      - george-edison55-precise-backports
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-3.6
                  packages:
                      - clang-3.6
                      - cmake
                      - cmake-data
        - os: linux
          compiler: gcc
          env: COMPILER=g++-5 BUILD_TYPE=Release
          addons:
              apt:
                  sources:
                      - george-edison55-precise-backports
                      - ubuntu-toolchain-r-test
                  packages:
                      - cmake
                      - cmake-data
                      - g++-5

install:
    - |
      if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
          brew install cmake
      fi

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script: cmake --build build

