# Exported from Kompositum > Settings > Export YAML
version: 1.0.0.{build}
os:
- Windows Server 2012 R2
environment:
  BUILD_TYPE: Release
  ARCH: Win64
  matrix:
  - GENERATOR: Visual Studio 14 2015 %ARCH%
  - GENERATOR: Visual Studio 12 2013 %ARCH%
build_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    cmake -H. -Bbuild -G"%GENERATOR%"

    cmake --build build --config %BUILD_TYPE%