# build version
version: 1.0.0.{build}

# branches to build
branches:
  only:
    - appveyor_support
  # whitelist
  
environment:
  BUILD_TYPE: Release
  ARCH: Win64
  matrix:
#    - GENERATOR: Visual Studio 14 2015
    - GENERATOR: Visual Studio 14 2015 %ARCH%
#    - GENERATOR: Visual Studio 12 2013
    - GENERATOR: Visual Studio 12 2013 %ARCH%

# CMAKE_BUILD_TYPE=None Debug Release RelWithDebInfo
# -H. path to source
# -B path to build in
before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake -H. -Bbuild -G"%GENERATOR%"
  
build_script:
  - cmake --build build --config %BUILD_TYPE%